---
title: "d1afternoon_explorer"
output: html_document
date: "2024-09-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(palmerpenguins)
library(ggthemes)

```


```{r}

head(penguins)

glimpse(penguins)

?penguins

```



```{r}

penguins[,"island"]

penguins[2, c("island","species")]

penguins[2, 2]`

```


```{r}

#mapping = mapping between your data sets and aes = aesthetic properties of your figure 

ggplot(data = penguins, 
       mapping = aes(x = flipper_length_mm, 
                     y = body_mass_g, 
                     color = species, 
                     shape = species)) +
       geom_point() +
       scale_color_colorblind() +
       geom_smooth(method = "lm")


       theme_minimal() +
       xlab("Flipper Length (mm)") +
       ylab("Body Mass (g)") +
       ggtitle("Comparing flipper length vs body mass in different penguin species")

#A way to use a manual color palette: scale_color_manual(values = c("red", "black", "lightblue")) -> can also use hex color codes + popular one is called colorbrewer

colnames(penguins)[1] <- "Species"
       
ggplot(data = penguins) +
  geom_point(mapping = aes(x = flipper_length_mm, 
                           y = body_mass_g, 
                           color = Species, 
                           shape = Species)) +
  geom_smooth(mapping = aes(x = flipper_length_mm, 
                            y = body_mass_g), 
              method = "lm") +
  scale_color_colorblind() + 
  theme_minimal() +
  xlab("Flipper Length (mm)") +
  ylab("Body Mass (g)") +
  ggtitle("Comparing flipper length (mm) vs. body mass (g) in different penguin species")

ggsave(filename = "penguin_scatterplot.pdf")
       
```



```{r}

#Does bill length or depth depend on sex of the penguins 

#Histograms -> creating bins 

colnames(penguins)[7] <- "Sex"

ggplot(data = penguins %>% filter(Sex == "male"), 
       mapping = aes(x = bill_length_mm), ) +
  geom_histogram() +
  theme_minimal()

ggplot(data = penguins %>% filter(Sex == "female"), 
       mapping = aes(x=bill_length_mm), ) +
  geom_histogram() +
  theme_minimal()

ggplot(data = penguins, 
       mapping = aes(x=bill_length_mm, 
                     fill = Sex)) +
  scale_fill_colorblind() +
  geom_histogram(position = "identity", 
                 alpha = 0.5) +
  theme_minimal() +
  xlab("Bill Length (mm)") +
  ylab("Frequency") +
  facet_grid(. ~ Sex)

ggplot(data = penguins, 
       mapping = aes(x=bill_length_mm, 
                     fill = Sex)) +
  scale_fill_colorblind() +
  geom_histogram(position = "identity", 
                 alpha = 0.5) +
  theme_minimal() +
  xlab("Bill Length (mm)") +
  ylab("Frequency") +
  facet_grid(Sex ~ .)

ggplot(data = penguins, 
       mapping = aes(x=bill_length_mm, 
                     fill = Sex)) +
  scale_fill_colorblind() +
  geom_histogram(position = "identity", 
                 alpha = 0.5) +
  xlab("Bill Length (mm)") +
  ylab("Frequency") +
  facet_grid(Sex ~ Species) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))


```


```{r}

#Has flipper length gone up or down over the years?
ggplot(data = penguins, 
       mapping = aes(x = body_mass_g, 
                     fill = Sex)) +
  geom_boxplot() +
  scale_fill_colorblind() +
  xlab("Year") +
  ylab("Body mass (g)") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) 


ggplot(data = penguins, 
       mapping = aes(x = factor(year), 
                     y = body_mass_g, 
                     fill = Sex)) +
  geom_boxplot() +
  facet_grid(island ~ Species) +
  xlab("Year") +
  ylab("Body mass (g)") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) 

ggplot(data = penguins, 
       mapping = aes(x = factor(year), 
                     y = body_mass_g, 
                     fill = Sex)) +
  geom_violin() +
  facet_grid(island ~ Species) +
  xlab("Year") +
  ylab("Body mass (g)") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) 



ggplot(data = penguins %>% filter(!is.na(Sex)), 
       mapping = aes(x = bill_length_mm, color = Sex)) +
  scale_fill_colorblind() +
  geom_density() +
  theme_classic()


```


